= Jumpstart your career with Fast Retailing 
Kenichi Shibata <kenichi.shibata@fastretailing.com>
v1.0 2015-10-12
Hi! My name is Kenichi Shibata, an Information Technology (IT) engineer in Fast Retailing. Today, we will discuss about improving your career as an IT professional. As a guide for the job seekers, we would briefly touch the topics to get your career a fruitful take off. If you are just starting on your career or either an experienced professional, this post will be equally useful and relevant for you.

== Opportunities!
Let's start with opportunities. In order for us to be successful, we must first be afforded with several opportunities to make us better engineers. Prospects in working with IT companies ultimately boils down to one of two choices namely: working in a small startup enterprise or in a well-established company with years of proficiency in this field and stable infrastructure. Let's differentiate working with the startup first.

=== The Startups
https://www.quora.com/Is-it-more-valuable-to-gain-experience-in-starting-a-start-up-or-to-have-experience-in-the-industry-where-you-want-to-start-a-company[They] say the best way to learn on how to be a full-fledged and skilled engineer is to get your hands dirty and develop something! In this regard, the startups definitely win since you will be able to develop small to large projects depending on the success of the startup. You will be able to gain tons of experience by working with people who are in the same level as you and because there is no bureaucracy in it and developers are usually the heart of the business. Also, the margin for error is big since you are in the startup and no one expects you to get everything right in the first try. The advantage of this is that you as an engineer will have more freedom to do the things you really love. Nevertheless, with all these advantages; there are lots of disadvantages. First, there is no reliable infrastructure to host your codes in the net (this is now changing with the advent of the cloud). Second, there aren’t a lot of resources to buy hardware, software, peopleware and everything that you will need for a long-term large scale project. And most of all, as a developer you will always feel that the company will always short-change you. Maybe the company has not yet ascended and there are no real resources to give benefits to its employees. To top it all off, the company might capsize anytime taking you along with it. Whatever the reason is, choosing to jumpstart your career in a startup company might not be the best decision you would ever make. So let's move on your career in a major company with real and reliable resources. 

=== The Major IT company
Working with a major IT company will be absolutely good for your family or savings. You will have a stable job with great benefits as well as a nice title to your resume. Through this, you will be able to go from one company into another whenever you wish! On most occasions, there are even parties in your office area with great food and beverages and lots of major events like hackathons and conventions that other companies will attend to. The greatest benefit from working on a major IT company is the peopleware. There are lots of great engineers that you can work with and share ideas with. You won’t need to do a whole lot of things because everything will be in there. Everything is set and everything is working on its proper place. You will be happy thinking you just have the best job in the world at least for a while. You, as an engineer, will no longer be mentally challenged by the tasks that the company will give you and everything seems to be in routine. Being an IT professional to this company will make you feel that it’s a part of your system and your skills will eventually be outdated. And while there may be some companies that will still give you projects from time to time, it will not be as earth shattering as it will be if you would work in a startup company. In the future, there are lots of your colleagues who are leading the innovation in the technological world while you are stuck maintaining your Java Server Pages (JSP) system simply because it pays well. Now we establish the best and the worst of working in both companies.

=== The Major Startup Company
Have you ever heard of the company Wearex? It is not a startup company and neither a major IT company with the task of maintaining its multimillion legacy systems. It is a technologically apt firm with an appetite to always innovate without reinventing the wheel. The bottom line is that this is a company with the growth of the startup company and with the resources of the Major IT Company. How? The company is owned by Fast Retailing! A company who got its roots by retailing and is a success story worthy of its own blog post. Fast Retailing aims to forever change the playing field in retailing by innovation user/customer experience. It is a company who dares to go beyond the borders.

=== The Strategy Build
Is there any way to become successful? Yes, there is! Join a small company under a visionary leader who finds talented individuals that would build the future! You know what it is—Wearex! What’s your strategy? Jumpstart your career with us!
